### ISSUE TITLE
_orig_terms kept on detached post

### ISSUE THREAD

**Issue by mikeselander** [Automattic/aggregator#47]
Not sure if this is intentional or not, but thought I'd bring it up - when a post is detached, the `_aggregator_orig_post_id ` and `_aggregator_orig_blog_id ` meta keys are deleted, but `_orig_terms` is left behind. I would have expected that this value would be deleted alongside the others.

**Comment by philipjohn** [comment]
Ah, this isn't a problem of detaching but of aggregation, so you found a problem just a different one :)

`_orig_terms` is used to store the original taxonomy terms assigned to a post. When a child post is created, a cron event is scheduled and when that event runs [we grab the terms](https://github.com/Automattic/aggregator/blob/8f9d1109878109a044b79b5342aaa268befb986a/class-aggregate.php#L646) to assign them to the post.

The problem here is that once we've done so, we're not clearly out the post meta which we should.

**Comment by mikeselander** [comment]
Ah, I see - that makes more sense!
