### ISSUE TITLE
Gutenberg Support

### ISSUE THREAD

**Issue by scottbasgaard** [Automattic/aggregator#69]
Awesome plugin @philipjohn, just opening a ticket to log issue with Gutenberg.

Gonna do some digging into it but it looks like we'll need to add a few other hooks for it to fire and support publish events there.

**Comment by scottbasgaard** [comment]
Looks like it's because `save_post` is wrapped in is_admin().

**Comment by scottbasgaard** [comment]
Something to do with is_admin() and `save_post`

**Comment by philipjohn** [comment]
Thanks for taking a look @scottbasgaard ! We never did get this plugin onto VIP for anyone, and it probably needs more work. Meanwhile, Syndication is probably still a better choice. Also, have a chat with Human Made about what they're using instead of this.

It's likely that we'll officially deprecate this one soon I'm afraid, as it doesn't get much use.

**Comment by scottbasgaard** [comment]
Good to know and thanks @philipjohn!
